# Generated by Django 4.0.10 on 2023-08-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0004_alter_customer_email_alter_trainer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trainer',
            field=models.CharField(max_length=100),
        ),
    ]
